function pieces () {
	
}
let mySprite3: Sprite = null
let mySprite2: Sprite = null
scene.setBackgroundColor(15)
tiles.setCurrentTilemap(tileUtil.createSmallMap(tilemap`level2`))
namespace userconfig {
    export const ARCADE_SCREEN_WIDTH = 150
    export const ARCADE_SCREEN_HEIGHT = 150
}
let hand = sprites.create(img`
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f1111111dbf......
    ......fd1111111ddf......
    ......fd111111dddf......
    ......fd111ddddddf......
    ......fd111ddddddf......
    ......fd1dddddddbf......
    ......fd1dfbddbbff......
    ......fbddfcdbbcf.......
    .....ffffccddbfff.......
    ....fcb1bbbfcffff.......
    ....f1b1dcffffffff......
    ....fdfdf..ffffffffff...
    .....f.f.....ffffff.....
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(hand, 50, 50)
let target = sprites.create(img`
    5 
    `, SpriteKind.Player)
target.setFlag(SpriteFlag.Ghost, true)
for (let index = 0; index <= 7; index++) {
    mySprite2 = sprites.create(assets.image`blackPawn`, SpriteKind.Player)
    tiles.placeOnTile(mySprite2, tiles.getTileLocation(index, 1))
    mySprite3 = sprites.create(assets.image`myImage0`, SpriteKind.Player)
    tiles.placeOnTile(mySprite3, tiles.getTileLocation(index, 6))
}
let towerB = sprites.create(assets.image`Tower`, SpriteKind.Player)
tiles.placeOnTile(towerB, tiles.getTileLocation(0, 0))
let towerW = sprites.create(assets.image`Tower0`, SpriteKind.Player)
tiles.placeOnTile(towerW, tiles.getTileLocation(0, 7))
tiles.placeOnTile(towerW, tiles.getTileLocation(0, 0))
let list = [
assets.image`blackPawn`,
assets.image`myImage0`,
assets.image`Tower`,
assets.image`Tower0`,
0
]
pieces()
game.onUpdate(function () {
    target.top = target.top
    target.x = target.top - 2
})
